version: '3.8'

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile.service
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV_DATABASE_URL=${ENV_DATABASE_URL}
    networks:
      - mynab-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    depends_on:
      - service
    environment:
      - VITE_API_URL=http://service:8000
    networks:
      - mynab-network

networks:
  mynab-network:
    driver: bridge