"""files list

Revision ID: 9d9eae723fcb
Revises: fa3a999a914a
Create Date: 2025-06-25 20:28:27.915294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9eae723fcb'
down_revision: Union[str, None] = 'fa3a999a914a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_base64', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mynab.auth_user.id'], name=op.f('files_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('files_pkey')),
    schema='mynab'
    )
    op.drop_table('budget_entry_category', schema='mynab')
    op.drop_table('budget_category', schema='mynab')
    op.add_column('budget_entry', sa.Column('file_id', sa.Integer(), nullable=True), schema='mynab')
    op.create_foreign_key(op.f('budget_entry_file_id_fkey'), 'budget_entry', 'files', ['file_id'], ['id'], source_schema='mynab', referent_schema='mynab')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('budget_entry_file_id_fkey'), 'budget_entry', schema='mynab', type_='foreignkey')
    op.drop_column('budget_entry', 'file_id', schema='mynab')
    op.create_table('budget_entry_category',
    sa.Column('entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['mynab.budget_category.id'], name='budget_entry_category_category_id_fkey'),
    sa.ForeignKeyConstraint(['entry_id'], ['mynab.budget_entry.id'], name='budget_entry_category_entry_id_fkey'),
    sa.PrimaryKeyConstraint('entry_id', 'category_id', name='budget_entry_category_pkey'),
    schema='mynab'
    )
    op.create_table('budget_category',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('mynab.budget_category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mynab.auth_user.id'], name='budget_category_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='budget_category_pkey'),
    schema='mynab'
    )
    op.drop_table('files', schema='mynab')
    # ### end Alembic commands ###
