"""Add national id to user

Revision ID: 273c749fb124
Revises: 1e4d22922830
Create Date: 2025-06-25 15:59:56.554050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273c749fb124'
down_revision: Union[str, None] = '1e4d22922830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('national_id', sa.String(length=20), nullable=True), schema='mynab')
    op.create_unique_constraint(op.f('auth_user_national_id_key'), 'auth_user', ['national_id'], schema='mynab')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('auth_user_national_id_key'), 'auth_user', schema='mynab', type_='unique')
    op.drop_column('auth_user', 'national_id', schema='mynab')
    # ### end Alembic commands ###
