"""Update decimal type of amount attribute

Revision ID: 68bf2a64ef93
Revises: 273c749fb124
Create Date: 2025-06-25 17:05:49.431281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68bf2a64ef93'
down_revision: Union[str, None] = '273c749fb124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_entry', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=38, scale=12),
               existing_nullable=False,
               schema='mynab')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_entry', 'amount',
               existing_type=sa.DECIMAL(precision=38, scale=12),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               schema='mynab')
    # ### end Alembic commands ###
