"""remove unique from reference id

Revision ID: b69a416cf2e9
Revises: e33a6d152213
Create Date: 2025-06-26 01:25:37.249438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69a416cf2e9'
down_revision: Union[str, None] = 'e33a6d152213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('budget_entry_reference_id_key', 'budget_entry', schema='mynab', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('budget_entry_reference_id_key', 'budget_entry', ['reference_id'], schema='mynab', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
