"""Add passwordless authentication support

Revision ID: a1b2c3d4e5f6
Revises: e981a5dc5b03
Create Date: 2025-07-19 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'e981a5dc5b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Make password nullable in auth_user table
    op.alter_column('auth_user', 'password',
                    existing_type=sa.LargeBinary(),
                    nullable=True,
                    schema='mynab')
    
    # Add auth_method column to auth_user table
    op.add_column('auth_user', 
                  sa.Column('auth_method', sa.String(length=20), 
                           nullable=False, server_default='password'),
                  schema='mynab')
    
    # Add email_verified column to auth_user table
    op.add_column('auth_user', 
                  sa.Column('email_verified', sa.Boolean(), 
                           nullable=False, server_default='false'),
                  schema='mynab')
    
    # Create auth_email_verification table
    op.create_table('auth_email_verification',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('verification_code', sa.String(length=10), nullable=False),
        sa.Column('code_type', sa.String(length=20), nullable=False),
        sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
        sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('auth_email_verification_pkey')),
        schema='mynab'
    )
    
    # Create index on email and code_type for faster lookups
    op.create_index(op.f('ix_auth_email_verification_email'), 'auth_email_verification', ['email'], schema='mynab')
    op.create_index(op.f('ix_auth_email_verification_code_type'), 'auth_email_verification', ['code_type'], schema='mynab')
    op.create_index(op.f('ix_auth_email_verification_expires_at'), 'auth_email_verification', ['expires_at'], schema='mynab')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index(op.f('ix_auth_email_verification_expires_at'), table_name='auth_email_verification', schema='mynab')
    op.drop_index(op.f('ix_auth_email_verification_code_type'), table_name='auth_email_verification', schema='mynab')
    op.drop_index(op.f('ix_auth_email_verification_email'), table_name='auth_email_verification', schema='mynab')
    
    # Drop auth_email_verification table
    op.drop_table('auth_email_verification', schema='mynab')
    
    # Remove email_verified column
    op.drop_column('auth_user', 'email_verified', schema='mynab')
    
    # Remove auth_method column
    op.drop_column('auth_user', 'auth_method', schema='mynab')
    
    # Make password non-nullable again
    op.alter_column('auth_user', 'password',
                    existing_type=sa.LargeBinary(),
                    nullable=False,
                    schema='mynab')
    
    # ### end Alembic commands ###
