"""Reference ID was added

Revision ID: e33a6d152213
Revises: 9d9eae723fcb
Create Date: 2025-06-25 20:43:44.191086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33a6d152213'
down_revision: Union[str, None] = '9d9eae723fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_entry', sa.Column('reference_id', sa.String(length=50), nullable=True), schema='mynab')
    op.create_unique_constraint(op.f('budget_entry_reference_id_key'), 'budget_entry', ['reference_id'], schema='mynab')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('budget_entry_reference_id_key'), 'budget_entry', schema='mynab', type_='unique')
    op.drop_column('budget_entry', 'reference_id', schema='mynab')
    # ### end Alembic commands ###
