"""New table for categorization

Revision ID: e981a5dc5b03
Revises: 433af6286ef4
Create Date: 2025-06-29 16:57:05.496877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e981a5dc5b03'
down_revision: Union[str, None] = '433af6286ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_transaction_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_key', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('budget_transaction_category_pkey')),
    sa.UniqueConstraint('category_key', name=op.f('budget_transaction_category_category_key_key')),
    schema='mynab'
    )
    op.add_column('budget_entry', sa.Column('category_id', sa.Integer(), nullable=True), schema='mynab')
    op.create_foreign_key(op.f('budget_entry_category_id_fkey'), 'budget_entry', 'budget_transaction_category', ['category_id'], ['id'], source_schema='mynab', referent_schema='mynab')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('budget_entry_category_id_fkey'), 'budget_entry', schema='mynab', type_='foreignkey')
    op.drop_column('budget_entry', 'category_id', schema='mynab')
    op.drop_table('budget_transaction_category', schema='mynab')
    # ### end Alembic commands ###
