"""add currency and source

Revision ID: fa3a999a914a
Revises: 68bf2a64ef93
Create Date: 2025-06-25 19:11:43.932170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3a999a914a'
down_revision: Union[str, None] = '68bf2a64ef93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_entry', sa.Column('currency', sa.String(length=3), nullable=True), schema='mynab')
    op.add_column('budget_entry', sa.Column('source', sa.String(length=50), nullable=True), schema='mynab')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_entry', 'source', schema='mynab')
    op.drop_column('budget_entry', 'currency', schema='mynab')
    # ### end Alembic commands ###
