"""Files per currency

Revision ID: 433af6286ef4
Revises: b69a416cf2e9
Create Date: 2025-06-27 00:38:56.938726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433af6286ef4'
down_revision: Union[str, None] = 'b69a416cf2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('currency', sa.String(length=3), nullable=True), schema='mynab')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'currency', schema='mynab')
    # ### end Alembic commands ###
